const CATEGORY_IMAGE_PATH = "uploads/images/category/"
const LOGO_SOURCE_PATH = "uploads/images/employer/"
const RESUME_PATH = "uploads/resume/"
const UPLOAD_CATEGORY_IMAGE_PATH = "public/" + CATEGORY_IMAGE_PATH
const UPLOAD_COMPANY_LOGO_PATH = "public/" + LOGO_SOURCE_PATH
const UPLOAD_RESUME_PATH = "public/" + RESUME_PATH

module.exports = {
  CATEGORY_IMAGE_PATH,
  LOGO_SOURCE_PATH,
  RESUME_PATH,
  UPLOAD_CATEGORY_IMAGE_PATH,
  UPLOAD_COMPANY_LOGO_PATH,
  UPLOAD_RESUME_PATH
}