const CATEGORY_IMAGE_PATH = "uploads/images/category/"
const LOGO_SOURCE_URL = "uploads/images/employer/"
const UPLOAD_CATEGORY_IMAGE_PATH = "public/" + CATEGORY_IMAGE_PATH
const UPLOAD_COMPANY_LOGO_PATH = "public/" + LOGO_SOURCE_URL

module.exports = {
  CATEGORY_IMAGE_PATH,
  LOGO_SOURCE_URL,
  UPLOAD_CATEGORY_IMAGE_PATH,
  UPLOAD_COMPANY_LOGO_PATH
}